### ISSUE TITLE
add site

### ISSUE THREAD

**Issue by zhulinghuanyu** [mai19950/free_site#1]
https://github.com/mkshare3/mkshare3.github.io
https://github.com/toshare5/toshare5.github.io
https://www.xfxssr.me/nav/blog

**Comment by zhulinghuanyu** [comment]
https://www.xfxssr.me/nav/blog

**Comment by mai19950** [comment]
https://github.com/mkshare3/mkshare3.github.io
这个更新不稳定的？2天前更新的了

**Comment by mai19950** [comment]
> https://github.com/mkshare3/mkshare3.github.io https://github.com/toshare5/toshare5.github.io https://www.xfxssr.me/nav/blog

https://github.com/mkshare3/mkshare3.github.io
这个更新不稳定的？2天前更新的了
